### ISSUE TITLE
Não deve-se omitir exceções

### ISSUE THREAD

**Issue by manoelcampos** [trasherdave/retorno-boleto-template-method#1]
https://github.com/trasherdave/retorno-boleto-template-method/blob/ad02cc42e8d6d7ccfdc969780c0c6029cd40c23f/src/main/java/com/david/retornoboleto/ProcessarBoletos.java#L39

Ver https://github.com/joaohora84/atividade1-strategy/issues/2
No seu caso, você usou um Logger no lugar de um print, que está correto. 
Com um logger, podemos salvar a mensagem de erro em um arquivo para consulta posterior.
Mas incluir apenas o log ou print, para quem está usando a app vai parecer que nenhum erro ocorreu.
Se o arquivo não pode ser lido por conta de um erro, o usuário precisa saber e não saberá.

**Comment by trasherdave** [comment]
Faz todo sentido.
Nesse caso, devo então adicionar uma mensagem ao usuário através de um print para que ele saiba, caso tenha um erro na leitura do arquivo?

**Comment by manoelcampos** [comment]
Sim, mas só no local onde chamar o método que gera a exceção. Como a app é console, lá fazemos um print. Se fosse web, mostrariamos uma msg na página

**Comment by trasherdave** [comment]
Perfeito, compreendi!
Alteração feita.
